# Generated by Django 3.0.3 on 2020-02-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='retry',
            field=models.IntegerField(default=3),
        ),
    ]
