# Generated by Django 3.0.3 on 2020-02-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0003_task_retry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scheduled_on',
            field=models.DateTimeField(),
        ),
    ]
